# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    # untuk folder upload gambar
    folder_produk: '%kernel.project_dir%/public_html/uploads/produk'
    folder_bukti: '%kernel.project_dir%/public_html/uploads/bukti'
    folder_profil: '%kernel.project_dir%/public_html/uploads/profil'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # untuk controller universal
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # untuk controller default
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # untuk controller admin
    App\Controller\Admin\:
        resource: '../src/Controller/Admin'
        tags: ['controller.service_arguments']